spring:
  application:
    name: neon-ark-intake-tracker

  datasource:
    url: jdbc:postgresql://localhost:5437/intake_tracker
    driver-class-name: org.postgresql.Driver
    username: neonark
    password: neonarkpass

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

server:
  port: 8080