CREATE TABLE creatures
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(120)                            NOT NULL,
    species      VARCHAR(120)                            NOT NULL,
    danger_level VARCHAR(30)                             NOT NULL,
    condition    VARCHAR(30)                             NOT NULL,
    notes        TEXT,
    habitat_id   BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_creatures PRIMARY KEY (id)
);